import React, { useEffect, useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import { buildBacktestExportData, buildLiveJournalExportData, buildMt5ReportExportData } from '../utils/reportExportData';
import { formatNumber, formatUsd } from '../utils/formatters';

type ReportKind = 'mt5' | 'session' | 'live';

export default function ReportPrint({ kind }: { kind: ReportKind }) {
  const params = useParams();
  const id = params.reportId || params.sessionId || params.accountId || '';
  const [raw, setRaw] = useState<any | null>(null);
  const [trades, setTrades] = useState<any[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let active = true;
    const load = async () => {
      setLoading(true);
      setError(null);
      try {
        if (kind === 'mt5') {
          const res = await fetch(`/api/mt5-reports/sessions/${id}`);
          const body = await res.json();
          if (!res.ok) throw new Error(body.error || 'MT5 report not found');
          if (active) setRaw(body);
        } else if (kind === 'session') {
          const res = await fetch(`/api/sessions/${id}`);
          const body = await res.json();
          if (!res.ok) throw new Error(body.error || 'Session not found');
          if (active) setRaw(body);
        } else {
          const [accountsRes, summaryRes, tradesRes] = await Promise.all([
            fetch('/api/accounts'),
            fetch(`/api/live-trades/summary?accountId=${id}`),
            fetch(`/api/live-trades?accountId=${id}`),
          ]);
          const accounts = await accountsRes.json();
          const summary = await summaryRes.json();
          const liveTrades = await tradesRes.json();
          if (!accountsRes.ok || !summaryRes.ok || !tradesRes.ok) throw new Error('Live report data not found');
          if (active) {
            setRaw({ account: accounts.find((a: any) => a.id === id), summary });
            setTrades(Array.isArray(liveTrades) ? liveTrades : []);
          }
        }
      } catch (err: any) {
        if (active) setError(err.message || 'Failed to load report');
      } finally {
        if (active) setLoading(false);
      }
    };
    load();
    return () => { active = false; };
  }, [id, kind]);

  const report = useMemo(() => {
    if (!raw) return null;
    if (kind === 'mt5') return buildMt5ReportExportData(raw);
    if (kind === 'session') return buildBacktestExportData(raw);
    return buildLiveJournalExportData({ account: raw.account, summary: raw.summary, trades });
  }, [kind, raw, trades]);

  if (loading) return <div className="print-shell">Loading printable report...</div>;
  if (error || !report) return <div className="print-shell text-red-700">{error || 'Report unavailable.'}</div>;

  return (
    <div className="print-shell">
      <div className="print-toolbar no-print">
        <button onClick={() => window.print()}>Print / Save as PDF</button>
        <span>Preview report before saving.</span>
      </div>

      <section className="print-page cover-page">
        <div className="brand">ReplayFX Journal</div>
        <h1>{report.title}</h1>
        <p className="subtitle">{report.subtitle}</p>
        {'verdict' in report && (
          <div className="verdict-box">
            <strong>Verdict: {report.verdict?.label || 'N/A'} {report.verdict?.score !== undefined ? `(${report.verdict.score}/100)` : ''}</strong>
            <p>{report.verdictText || 'No verdict available.'}</p>
          </div>
        )}
        <div className="cover-metrics">
          {report.metrics.slice(0, 5).map(([label, value]: any) => (
            <div key={label}>
              <span>{label}</span>
              <strong>{formatValue(value)}</strong>
            </div>
          ))}
        </div>
        <div className="meta-grid">
          {report.metadata.map(([label, value]: any) => <InfoCell key={label} label={label} value={value} />)}
        </div>
        <p className="muted cover-note">Generated by ReplayFX Journal. Account numbers are masked where applicable. For research, archive, and trading review only.</p>
      </section>

      <section className="print-page">
        <h2>Key Metrics</h2>
        <div className="metric-grid">
          {report.metrics.map(([label, value]: any) => <InfoCell key={label} label={label} value={formatValue(value)} />)}
        </div>
      </section>

      <section className="print-page">
        <h2>Charts / Curves</h2>
        <CurvePreview rows={(report as any).equityPoints || []} />
        <p className="muted">
          {((report as any).equityPoints || []).length
            ? 'Balance/equity curve is based on tester graph points.'
            : 'Tester graph was not uploaded; curve is approximated or unavailable.'}
        </p>
      </section>

      <section className="print-page">
        <h2>Findings / Diagnostics</h2>
        {(report.findings || []).length ? (
          <div className="finding-list">
            {report.findings.map((finding: any, index: number) => (
              <div key={`${finding.title}-${index}`} className={`finding finding-${String(finding.severity || 'INFO').toLowerCase()}`}>
                <strong>{finding.severity || 'INFO'} · {finding.title}</strong>
                <p>{finding.explanation}</p>
                <small>{finding.suggestedFix}</small>
              </div>
            ))}
          </div>
        ) : (
          <p className="muted">No diagnostics generated for this report.</p>
        )}
      </section>

      <section className="print-page">
        <h2>Indonesian Auto Analysis</h2>
        {Object.entries(report.analysis || {}).length ? Object.entries(report.analysis).map(([key, value]) => (
          <div key={key} className="analysis-block">
            <h3>{key.replace(/([A-Z])/g, ' $1')}</h3>
            <p>{String(value)}</p>
          </div>
        )) : <p className="muted">No written analysis available.</p>}
      </section>

      <section className="print-page">
        <h2>Calendar / Daily Review</h2>
        <DataTable
          columns={['Date', 'PnL', 'Trades', 'Winrate', 'Best', 'Worst']}
          rows={(report.daily || []).map((d: any) => [
            d.date,
            formatUsd(d.totalPnl),
            d.tradeCount,
            `${formatNumber(d.winrate, 2)}%`,
            d.bestTrade ? formatUsd(d.bestTrade.netPnlUsd ?? d.bestTrade.profit) : '-',
            d.worstTrade ? formatUsd(d.worstTrade.netPnlUsd ?? d.worstTrade.profit) : '-',
          ])}
        />
      </section>

      <section className="print-page">
        <h2>Best / Worst Trades</h2>
        <div className="two-col">
          <TradeMiniTable title="Top 10 Best Trades" rows={report.bestTrades || []} />
          <TradeMiniTable title="Top 10 Worst Trades" rows={report.worstTrades || []} />
        </div>
      </section>

      <section className="print-page">
        <h2>Detailed Tables</h2>
        <TradeMiniTable title="Rebuilt / Session Trades" rows={(report.trades || []).slice(0, 80)} />
        {(report as any).deals?.length ? <p className="muted">Deals rows: {(report as any).deals.length}. Orders rows: {(report as any).orders?.length || 0}.</p> : null}
        {(report as any).settings ? <KeyValuePrint title="Settings / EA Inputs" rows={(report as any).settings} /> : null}
      </section>
    </div>
  );
}

function formatValue(value: any) {
  if (typeof value === 'number') return Math.abs(value) > 20 ? formatUsd(value) : formatNumber(value, 4);
  return value ?? '-';
}

function InfoCell({ label, value }: { label: string; value: any }) {
  return (
    <div className="info-cell">
      <span>{label}</span>
      <strong>{String(value ?? '-')}</strong>
    </div>
  );
}

function CurvePreview({ rows }: { rows: any[] }) {
  const data = (rows || []).slice(0, 160);
  if (!data.length) return <div className="empty-chart">No graph data available.</div>;
  const values = data.map((row) => Number(row.equity ?? row.balance ?? 0));
  const min = Math.min(...values);
  const max = Math.max(...values);
  const range = max - min || 1;
  const points = values.map((value, index) => {
    const x = (index / Math.max(1, values.length - 1)) * 760;
    const y = 220 - ((value - min) / range) * 190;
    return `${x.toFixed(1)},${y.toFixed(1)}`;
  }).join(' ');
  return (
    <svg className="curve-svg" viewBox="0 0 800 260" role="img">
      <rect x="0" y="0" width="800" height="260" fill="#f8fafc" />
      <polyline points={points} fill="none" stroke="#0ea5e9" strokeWidth="3" transform="translate(20 20)" />
      <text x="20" y="245" fill="#475569" fontSize="12">Min {min.toFixed(2)} · Max {max.toFixed(2)}</text>
    </svg>
  );
}

function DataTable({ columns, rows }: { columns: string[]; rows: any[][] }) {
  return (
    <table className="print-table">
      <thead><tr>{columns.map((c) => <th key={c}>{c}</th>)}</tr></thead>
      <tbody>{rows.length ? rows.map((row, index) => <tr key={index}>{row.map((cell, i) => <td key={i}>{cell}</td>)}</tr>) : <tr><td colSpan={columns.length}>No rows.</td></tr>}</tbody>
    </table>
  );
}

function TradeMiniTable({ title, rows }: { title: string; rows: any[] }) {
  return (
    <div>
      <h3>{title}</h3>
      <DataTable
        columns={['Time', 'Symbol', 'Side', 'PnL', 'Notes']}
        rows={(rows || []).map((t) => [
          String(t.exitTime || t.closeTime || t.openTime || t.entryTime || '').slice(0, 16),
          t.symbol || '-',
          t.side || '-',
          formatUsd(t.netPnlUsd ?? t.profit ?? t.pnl ?? 0),
          t.notes || '-',
        ])}
      />
    </div>
  );
}

function KeyValuePrint({ title, rows }: { title: string; rows: Record<string, any> }) {
  return (
    <div>
      <h3>{title}</h3>
      <DataTable columns={['Key', 'Value']} rows={Object.entries(rows || {}).slice(0, 80)} />
    </div>
  );
}
